### ISSUE TITLE
Unable to Open Device Error

### ISSUE THREAD

**Issue by Kroltez** [RussTheAerialist/node-spi#26]
Got this error on raspberry pi:
```
{ MODE: { MODE_0: 0, MODE_1: 1, MODE_2: 2, MODE_3: 3 },
  CS: { none: 64, high: 4, low: 0 },
  ORDER: { msb: false, lsb: true },
  Spi: [Function: Spi] }
Spi { _spi: _spi {}, device: '/dev/spidev.0.0' }
/home/pi/node_modules/spi/spi.js:65
    return this._spi.open(this.device);
                     ^

TypeError: Unable to open device
    at Spi.open (/home/pi/node_modules/spi/spi.js:65:22)
    at /home/pi/code/ThunderBoard/ExampleA.js:9:18
    at new Spi (/home/pi/node_modules/spi/spi.js:60:29)
    at Object.<anonymous> (/home/pi/code/ThunderBoard/ExampleA.js:7:11)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)

```
Using this code:

```
// Create a ThunderboardReact object
var ThunderboardReact = require('node-thunderboard-react');
var thunder = new ThunderboardReact();

var SPI = require('spi');
var spi = new SPI.Spi('/dev/spidev.0.0', {
	'mode': SPI.MODE['MODE_0']
}, function(s){s.open();});

var txbuf = new Buffer([ 0x23, 0x48, 0xAF, 0x19, 0x19, 0x19]);
var rxbuf = new Buffer([ 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]);

// Initialize the ThunderboardReact object
thunder.init((error) => {
  // Discover the Thunderboard React Board Kit
  thunder.startDiscovery((device) => {
    console.log('- Found ' + device.localName);
    // Stop the discovery process
    thunder.stopDiscovery();
    // Connect to the found device
    device.connect((error) => {
      console.log('- Connected ' + device.localName);
      // Get the sensored data
      //device.getBatteryLevel((error, res) => {
		  //console.log('- Battery Level : ' + res.level + ' %');

	  //});
      getEnvironmentalSensing(device);
      //startMonitorOrientation(device);
    });
  });
});

//Get the sensored data
function getEnvironmentalSensing(device) {
  device.getEnvironmentalSensing((error, res) => {
    // Show the data
    console.log('- Sensored data:');
    console.log('  - Humidity    : ' + res.humidity + ' %');
    txbuf[0] = res.humidity;
    console.log('  - Temperature : ' + res.temperature + ' °C');
    txbuf[2] = res.temperature;
    console.log('  - UV Index    : ' + res.uvIndex);
    txbuf[4] = res.uvIndex;
    //// Disconnect the device
    //device.disconnect(() => {
      //console.log('- Disconnected ' + device.localName);
      //process.exit();
    //});
    spi.transfer(txbuf, rxbuf, function(device, buf) {
	//rxbuf and buf are same thing
	});
  });
}


// Monitor the sensored data
function startMonitorOrientation(device) {
  // Start to monitor the orientation of the device
  device.startMonitorOrientation((error) => {
    if(error) {
      console.log(error.toString());
      process.exit();
    }
  });

  // Set a listener for orientation events fired on the ThunderboardReactDevice object
  device.on('orientation', (res) => {
    // Show the event data
    console.log('- Orientation:');
    console.log('  - alpha :' + res.alpha + '°');
    console.log('  - beta  :' + res.beta + '°');
    console.log('  - gamma :' + res.gamma + '°');
  });

  // Stop to monitor and disconnect the device in 5 seconds
  //setTimeout(() => {
    //device.stopMonitorOrientation((error) => {
      //// Disconnect the device
      //device.disconnect(() => {
		
        //console.log('- Disconnected ' + device.localName);
        //process.exit();
      //});
    //});
  //}, 5000);
}

```

**Comment by graysonarts** [comment]
what have you done to debug the issue so far?  Does the end point ( /dev/spidev.0.0 ) exist?  This module is basically dead because I don't have the time or inclination to continue supporting it.  There are other modules which have superseded the functionality here and handling newer versions of node.

The one I've been recommending is https://github.com/natevw/pi-spi

**Comment by Kroltez** [comment]
Thankyou, yes you were right it was /de/spidev0.0 ! the name was wrong
