### ISSUE TITLE
TypeError: Argument 0 must be an integer

### ISSUE THREAD

**Issue by jbaldwinroberts** [RussTheAerialist/node-spi#6]
HI,

Thanks for creating this, it will be very useful if I can get it working.

When I try and run the example code on raspbian using node v0.10.7 and  npm 1.2.21 I get the error:

Trace: Setting mode=undefined
    at new Spi (/home/pi/Programming/node_modules/spi/spi.js:51:15)
    at Object.<anonymous> (/home/pi/Programming/spi.js:3:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:901:3

/home/pi/Programming/node_modules/spi/spi.js:52
      this._spi[attrname](value);
                         ^
TypeError: Argument 0 must be an integer
    at new Spi (/home/pi/Programming/node_modules/spi/spi.js:52:26)
    at Object.<anonymous> (/home/pi/Programming/spi.js:3:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:901:3

Has anyone else had this, is there a solution?

Thanks
Joe

**Comment by RussTheAerialist** [comment]
for the 0.2.0 release, I've changed the way it all works to clean some stuff up.  I'm going to update the documentation before 0.2.0 is released.
